from django.urls import path
from . import views
from register import views as v

urlpatterns=[
    path("home/",views.home,name="Home"),
    path("admin_entry/",views.admin_entry,name="Admin - entry"),
    path("entry_edited/entry=<int:id>/",views.entry_edited,name="Admin - entry edited"),
    path("entry_deleted/entry=<int:id>/",views.entry_deleted,name="Admin - entry deleted"),
    path("admin_survey/",views.admin_survey,name="Admin - survey"),
    path("admin_user/",views.admin_user,name="Admin - user"),
    path("login/",v.Login_cec,name="Login"),
    path("survey=<str:title>/entry=<int:id>/",views.display_entry,name="See entry"),
    path("survey=<str:title>/all/",views.display_survey,name="See survey"),
    path("survey=<str:title>/report/",views.survey_report,name="See survey"),
    path("new_entry/",views.new,name="New Entry"),
    path("entry_done/",views.plane_entry_finish,name="Entry added"),
    path("train_entry_finished/",views.train_entry_finish,name="Entry added - Train"),
    path("other_entry_finished/",views.other_entry_finish,name="Entry added - Other"),
    path("none_entry_finished/",views.none_entry_finish,name="Entry added - None"),
    path("all_surveys/",views.surveys,name="All Surveys"),
    path("register/",v.register,name="Register"),
    path("login_success/", views.login_success, name="Login success"),
    path("logout/", views.logout_success, name="Logout success"),
    path("plane_survey/",views.plane_survey,name="Plane survey"),
    path("train_survey/",views.train_survey,name="Train survey"),
    path("other_survey/",views.other_survey,name="Other survey"),
    path("operator_survey/",views.operator_entry,name="Other survey"),
    path("none_survey_confirm/",views.none_survey,name="None survey"),
    path("admin_page/entry=<int:id>/edit/",views.entry_edit,name="Edit entry"),
    path("admin_page/entry=<int:id>/delete/",views.entry_delete,name="Delete entry"),
    path("admin_page/user=<str:name>/edit/",views.user_change,name="Edit User"),
    path("admin_page/user_changed/user=<str:name>/",views.user_changed,name="User changed"),
    path("admin_page/survey_add/",views.add_survey,name="Add survey"),
    path("admin_page/survey_added/",views.survey_added,name="Survey added"),
    path("admin_page/survey_edit/survey=<str:title>/",views.survey_change,name="Survey change"),
    path("admin_page/survey_changed/survey=<str:title>/",views.survey_changed,name="Survey change - redirecting..."),
    path("admin_page/survey_delete/survey=<str:title>/",views.delete_survey,name="Delete survey"),
    path("admin_page/survey_deleted/survey=<str:title>/",views.survey_deleted,name="Survey deleted"),
    path("admin_page/entry_organize/redirect/",views.entry_organize_redirect,name="Entry organize - redirecting..."),
    path("admin_page/entry_organize/survey=<str:title>/transportation=<str:transportation>/review=<str:review>/category=<str:category>/order=<str:order>/",views.entry_organize,name="Entry filtered"),
    path("operator_survey/submitted/",views.operator_entry_submitted,name="Operator Entry Submitted"),
    path("operation_reports/",views.operation_reports,name="Operational Reports"),
    path("operation_report/<int:year>/<int:month>/",views.view_operation_report,name="View Operational Report")
]