# Generated by Django 5.1 on 2024-10-28 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 0, 0)),
        ),
    ]
