# Generated by Django 5.1 on 2024-10-28 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cec', '0004_survey_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='deadline',
            field=models.DateField(default=datetime.date(2099, 12, 31)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='opening',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
    ]
