# Generated by Django 5.1 on 2024-11-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cec', '0005_alter_survey_deadline_alter_survey_opening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorentry',
            name='survey',
        ),
    ]
