# Generated by Django 5.1 on 2024-11-02 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cec', '0008_operatorreport_delete_operatormodels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatorreport',
            old_name='ACB',
            new_name='ACA',
        ),
        migrations.RenameField(
            model_name='operatorreport',
            old_name='ACBA',
            new_name='ACAA',
        ),
        migrations.RenameField(
            model_name='operatorreport',
            old_name='ACBL',
            new_name='ACAL',
        ),
    ]
