# Generated by Django 5.1 on 2024-11-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cec', '0011_operatorreport_month_operatorreport_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorreport',
            name='Month_Text',
            field=models.CharField(default='Jan', max_length=3),
        ),
    ]
